services:
  db:
    image: mysql:8.0
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3307:3306"
    volumes:
      - todo_mysql_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: todo_app
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      JWT_SECRET: 123123az
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    stdin_open: true # Giữ cho container không bị đóng ngay lập tức (cần thiết cho React/Vue)

volumes:
  todo_mysql_data:
